### PR TITLE
added 2 more constellation stories. Also fixed formatting

### PR DESCRIPTION
**Pull request by dionkb**

### CODE REVIEW

**Comment by dionkb** [comment]
JJ: I also edited your paragraphs for grammar/spelling/etc. You should see the changes when you approve the push -DB

**Review by CristinaJoelle — APPROVED** [review]
Changes to the constellation page.

**Review by CristinaJoelle — APPROVED** [review]
Changes to the constellation page.

**Review by CristinaJoelle — APPROVED** [review]
Changes to the constellation page.

**Review by CristinaJoelle — APPROVED** [review]

**Pull request merged**
